Base_url: BEF0j5U1aNiqcQaDJ5c6RbH1OopOzrwyIq/EgrMUNtYOJclIj3EA2PENeD4vj1K3qfhi1HAtUsVFB/mPqPmClVCIkPW8Yk9ZnnzcWg==
Client_id: 9l8UvMi00MLGQvr9VaxJ059tRbprnNquSY3TeSAvvj2+V4XbdKI4sWiQ6coJTNkQA1zDn1Ap4QHbeY+M
Client_secret: A8CtJ90jh+aNEPJQjpcb9/JAxmo1v3BPgS6Zr0NA3rH41QTmaeMLm4oUKHtOqFjYXBeYTdtVrUwtY4mj
Customer_id: 7lL8GZzKA2SsA3eWbVZIAmKfveaCsZSzl68BEpuOGKZGLXKbuQk7fjx8IQlZMQ8AK4nuIV5xew1AqVQe
Refresh_token: wmfb37OZcYWu22344UOfcABrmTF03j4WzJ/C6aLcMXphz5oGSmsADvfuxCdvXC7ER87+7xcbdIf9RLO1
Token: pOl5oLFHfo4sNR4TBuBPzjiHEL+k1OY2jHDsm/V3BR84BeKaZZMD74wCSQmzzneYAT2NTS8dqT5TPzvi
